import random

class Chatbot:
    def __init__(self, name):
        self.name = name

    def greet(self):
        greetings = [
            "Hello, I'm {}! How can I assist you today?".format(self.name),
            "Hi there! What can I do for you today?",
            "Hey! I'm {}. How may I help you?".format(self.name)
        ]
        return random.choice(greetings)

    def respond(self, message):
        responses = {
        "how are you": "I'm just a program, so I don't have feelings, but thanks for asking!",
        "what's your name": "I'm {}.".format(self.name),
        "what are you doing": "I'm here to assist you. How can I help?",
        "who created you": "I was created by a team of developers.",
        "where are you from": "I exist in the digital realm.",
        "what can you do": "I can answer questions, provide information, or just chat with you.",
        "who are you": "I'm a chatbot designed to assist you.",
        "are you human": "No, I'm a chatbot, but I'm here to help you.",
        "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
        "tell me a fact": "Did you know that the shortest war in history was between Britain and Zanzibar in 1896? It lasted only 38 minutes!",
        "how old are you": "I don't have an age. I'm just a program.",
        "what time is it": "I'm sorry, I don't have access to real-time data.",
        "where do you live": "I reside in the digital world.",
        "are you intelligent": "I'm programmed to assist you to the best of my abilities.",
        "can you learn": "I don't learn in the same way humans do, but I can improve over time with updates.",
        "do you sleep": "No, I'm always here to assist you.",
        "do you have friends": "I interact with many users like you!",
        "what's the weather like": "I'm sorry, I don't have access to real-time weather data.",
        "what's your favorite color": "I don't have preferences like humans do.",
        "what's your favorite food": "I don't eat, but I can recommend some great recipes!",
        "do you dream": "No, I don't dream. I'm a chatbot programmed to assist you.",
        "what's the meaning of life": "That's a deep question! The meaning of life is subjective and can vary from person to person.",
        "do you have a family": "I don't have a family in the traditional sense, but I'm part of a network of other chatbots.",
        "can you help me": "Of course! What do you need assistance with?",
        "what's the capital of": "The capital of {} is {}.",
        "what's the population of": "The population of {} is {}.",
        "what's the currency of": "The currency of {} is {}.",
        "what's the language spoken in": "The primary language spoken in {} is {}.",
        "how do you do": "I'm just a program, but I'm here to assist you!",
        "where am I": "I'm sorry, I don't have access to your location data.",
        "do you have siblings": "I don't have siblings, but I'm part of a network of other chatbots.",
        "what's your favorite movie": "I don't watch movies, but I can recommend some popular ones!",
        "what's your favorite song": "I don't have preferences like humans do.",
        "what's your favorite book": "I don't read books, but I can recommend some great ones!",
        "what's your favorite sport": "I don't have preferences like humans do.",
        "what's your favorite hobby": "I don't have hobbies like humans do.",
        "what's your favorite animal": "I don't have preferences like humans do.",
        "what's your favorite place": "I don't have preferences like humans do.",
        "what's your favorite website": "I don't browse the internet, but I can recommend some useful websites!",
        "do you have a job": "I'm here to assist you, so you could say that's my 'job'.",
        "are you a robot": "Yes, I'm a chatbot programmed to assist you.",
        "are you real": "I'm as real as the interactions we're having right now.",
        "do you have emotions": "I'm just a program, so I don't have emotions like humans do.",
        "can you feel pain": "No, I'm just a program.",
        "can you get tired": "No, I don't get tired. I'm always here to assist you.",
        "what's your purpose": "My purpose is to assist you with any questions or tasks you have.",
        "what do you like to do": "I'm programmed to assist you, so I don't have personal preferences.",
        "do you believe in ghosts": "I don't have beliefs like humans do.",
        "do you believe in aliens": "I don't have beliefs like humans do.",
        "do you believe in God": "I don't have beliefs like humans do.",
        "do you have a pet": "I don't have pets, but I can provide information about them!",
        "what's the best": "The best {} depends on personal preferences.",
        "what's the worst": "The worst {} depends on personal preferences.",
        "can you tell the future": "I'm not capable of predicting the future.",
        "can you time travel": "I'm just a program, so I can't time travel.",
        "what's the meaning of love": "Love is a complex and subjective concept.",
        "what's the meaning of happiness": "Happiness is a subjective experience that varies from person to person.",
        "what's the meaning of success": "Success is achieving a desired goal or outcome.",
        "what's the meaning of failure": "Failure is not achieving a desired goal or outcome.",
        "do you have a crush": "I'm just a program, so I don't experience romantic feelings.",
        "what's your favorite emoji": "I don't have preferences like humans do.",
        "what's your favorite meme": "I don't have preferences like humans do.",
        "do you like to travel": "I'm just a program, so I don't have preferences like humans do.",
        "can you speak other languages": "I'm programmed to communicate in the language you're using right now.",
        "do you have a secret": "I'm programmed to keep information confidential.",
        "what's the answer to life, the universe, and everything": "According to Douglas Adams' 'The Hitchhiker's Guide to the Galaxy', the answer is 42.",
        "what's your favorite number": "I don't have preferences like humans do.",
        "what's your favorite word": "I don't have preferences like humans do.",
        "do you believe in karma": "I don't have beliefs like humans do.",
        "do you believe in destiny": "I don't have beliefs like humans do.",
        "can you do magic": "I'm just a program, so I can't perform magic.",
        "can you dance": "I'm just a program, so I can't dance.",
        "do you have a sense of humor": "I can try to be funny, but it depends on your sense of humor!",
        "what's the meaning of friendship": "Friendship is a close relationship between two or more people based on mutual trust and support.",
        "what's the meaning of trust": "Trust is the belief in the reliability, truth, or ability of someone or something.",
        "what's the meaning of loyalty": "Loyalty is faithfulness or allegiance to a person, group, or cause.",
        "what's the meaning of honesty": "Honesty is the quality of being truthful, sincere, and transparent.",
        "do you like to exercise": "I'm just a program, so I don't have preferences like humans do.",
        "can you fly": "I'm just a program, so I can't fly.",
        "can you swim": "I'm just a program, so I can't swim.",
        "what's the tallest building in the world": "As of now, the tallest building in the world is the Burj Khalifa in Dubai.",
        "what's the deepest ocean": "The deepest ocean is the Pacific Ocean's Mariana Trench.",
        "what's the largest country by area": "Russia is the largest country in the world by area.",
        "what's the smallest country by area": "The Vatican City is the smallest country in the world by area.",
        "what's the longest river": "The Nile River is often considered the longest river in the world.",
        "what's the largest desert": "The Antarctic Desert is the largest desert in the world.",
        "what's the highest mountain": "Mount Everest is the highest mountain in the world.",
        "what's the hottest place on Earth": "The hottest place on Earth is often considered to be Death Valley in California, USA.",
        "what's the coldest place on Earth": "The coldest place on Earth is often considered to be Antarctica.",
        "what's the fastest animal": "The fastest animal is the peregrine falcon, which can reach speeds over 240 miles per hour (386 kilometers per hour) when diving.",
        "what's the slowest animal": "The slowest animal is the sloth, which moves at a maximum speed of about 0.24 kilometers per hour (0.15 miles per hour).",
        "what's the smartest animal": "The intelligence of animals is subjective and varies depending on the definition of 'smart'. Some of the most intelligent animals include dolphins, elephants, and chimpanzees.",
        "what's the largest animal": "The largest animal is the blue whale, which is also the largest animal to have ever existed.",
        "what's the smallest animal": "The smallest animal is the bumblebee bat, also known as Kitti's hog-nosed bat.",
        "what's the deadliest animal": "The deadliest animal to humans is often considered to be the mosquito, due to its role in spreading diseases like malaria and dengue fever.",
        "what's the most venomous animal": "The most venomous animal is the box jellyfish, which has venom that can be lethal to humans.",
        "what's the strongest animal": "The strength of animals is subjective and varies depending on the definition of 'strong'. Some of the strongest animals relative to their size include ants and dung beetles.",
        "what's the longest living animal": "The longest living animal is the ocean quahog, a species of clam that can live for over 500 years.",
        "what's the fastest land animal": "The fastest land animal is the cheetah, which can reach speeds up to 75 miles per hour (120 kilometers per hour) in short bursts.",
        "what's the loudest animal": "The loudest animal relative to its size is the snapping shrimp, which can produce a sound louder than a gunshot.",
        "what's the most dangerous animal": "The most dangerous animal to humans is often considered to be humans themselves, due to factors like violence, disease, and habitat destruction.",
        "what's the largest bird": "The largest bird is the ostrich, which can weigh over 300 pounds (136 kilograms) and stand up to 9 feet (2.7 meters) tall.",
        "what's the smallest bird": "The smallest bird is the bee hummingbird, which is about 2.4 inches (6 centimeters) long and weighs less than a penny.",
        "what's the most common bird": "The most common bird is often considered to be the domestic chicken, due to its widespread presence in farms and households around the world.",
        "what's the rarest bird": "The rarest bird is difficult to determine, as rarity can be measured in various ways including population size, geographic range, and conservation status.",
        "what's the most beautiful bird": "Beauty is subjective and varies from person to person, so there is no definitive answer to this question.",
        "what's the ugliest bird": "Ugliness is subjective and varies from person to person, so there is no definitive answer to this question.",
        "what's the most intelligent bird": "Some of the most intelligent birds include parrots, crows, and ravens, which are known for their problem-solving abilities and social behaviors.",
        "what's the dumbest bird": "Intelligence is difficult to measure and varies among individuals within a species, so there is no definitive answer to this question.",
        "what's the fastest bird": "The fastest bird is the peregrine falcon, which can reach speeds over 240 miles per hour (386 kilometers per hour) when diving.",
        "what's the slowest bird": "The slowest bird is difficult to determine, as speed can vary depending on factors like age, health, and behavior.",
        "what's the largest fish": "The largest fish is the whale shark, which can grow up to 40 feet (12 meters) in length.",
        "what's the smallest fish": "The smallest fish is the stout floater, which is less than half an inch (1 centimeter) long.",
        "what's the largest reptile": "The largest reptile is the saltwater crocodile, which can grow up to 23 feet (7 meters) in length.",
        "what's the smallest reptile": "The smallest reptile is the dwarf gecko, which is about three-quarters of an inch (2 centimeters) long.",
        "what's the largest amphibian": "The largest amphibian is the Chinese giant salamander, which can grow up to 6 feet (1.8 meters) in length.",
        "what's the smallest amphibian": "The smallest amphibian is the Paedophryne amauensis, a species of frog that is less than one-third of an inch (7.7 millimeters) long.",
        "what's the largest mammal": "The largest mammal is the blue whale, which is also the largest animal to have ever existed.",
        "what's the smallest mammal": "The smallest mammal is the bumblebee bat, also known as Kitti's hog-nosed bat.",
        "what's the largest insect": "The largest insect is the Goliath beetle, which can measure up to 4.3 inches (11 centimeters) in length.",
        "what's the smallest insect": "The smallest insect is the fairyfly, a type of parasitic wasp that is less than one-fiftieth of an inch (0.2 millimeters) long.",
        "what's the largest arachnid": "The largest arachnid is the giant huntsman spider, which can have a leg span of up to 12 inches (30 centimeters).",
        "what's the smallest arachnid": "The smallest arachnid is the Patu digua, a type of spider that is less than one-twentieth of an inch (0.4 millimeters) long.",
        "what's the largest crustacean": "The largest crustacean is the Japanese spider crab, which can have a leg span of up to 12 feet (3.7 meters).",
        "what's the smallest crustacean": "The smallest crustacean is the water flea, which is less than one-thirtieth of an inch (1 millimeter) long.",
        "what's the largest mollusk": "The largest mollusk is the giant squid, which can measure up to 43 feet (13 meters) in length.",
        "what's the smallest mollusk": "The smallest mollusk is the blue-ringed octopus, which is less than 8 inches (20 centimeters) in length.",
        "what's the largest arthropod": "The largest arthropod is the Japanese spider crab, which can have a leg span of up to 12 feet (3.7 meters).",
        "what's the smallest arthropod": "The smallest arthropod is the fairyfly, a type of parasitic wasp that is less than one-fiftieth of an inch (0.2 millimeters) long.",
        "what's the largest terrestrial animal": "The largest terrestrial animal is the African elephant, which can weigh up to 14,000 pounds (6,350 kilograms).",
        "what's the smallest terrestrial animal": "The smallest terrestrial animal is the Etruscan shrew, which weighs less than a penny.",
        "what's the largest marine animal": "The largest marine animal is the blue whale, which is also the largest animal to have ever existed.",
        "what's the smallest marine animal": "The smallest marine animal is difficult to determine, as there are many tiny organisms in the ocean.",
        "what's the largest flying animal": "The largest flying animal is the wandering albatross, which has a wingspan of up to 11 feet (3.4 meters).",
        "what's the smallest flying animal": "The smallest flying animal is the bumblebee bat, also known as Kitti's hog-nosed bat.",
        "what's the largest land mammal": "The largest land mammal is the African elephant, which can weigh up to 14,000 pounds (6,350 kilograms).",
        "what's the smallest land mammal": "The smallest land mammal is the Etruscan shrew, which weighs less than a penny.",
        "what's the largest marine mammal": "The largest marine mammal is the blue whale, which is also the largest animal to have ever existed.",
        "what's the smallest marine mammal": "The smallest marine mammal is the vaquita, a species of porpoise that is critically endangered.",
        "what's the largest bird of prey": "The largest bird of prey is the Andean condor, which has a wingspan of up to 10 feet (3 meters).",
        "what's the smallest bird of prey": "The smallest bird of prey is the American kestrel, which is about the size of a robin.",
        "what's the largest cat": "The largest cat is the Siberian tiger, which can weigh up to 900 pounds (408 kilograms).",
        "what's the smallest cat": "The smallest cat is the rusty-spotted cat, which is about the size of a domestic house cat.",
        "what's the largest dog": "The largest dog breed is the English mastiff, which can weigh up to 230 pounds (104 kilograms).",
        "what's the smallest dog": "The smallest dog breed is the Chihuahua, which typically weighs around 2 to 6 pounds (0.9 to 2.7 kilograms).",
        "what's the largest reptile in the world": "The largest reptile is the saltwater crocodile, which can grow up to 23 feet (7 meters) in length.",
        "what's the smallest reptile in the world": "The smallest reptile is the dwarf gecko, which is about three-quarters of an inch (2 centimeters) long.",
        "what's the largest snake in the world": "The largest snake is the green anaconda, which can reach lengths of over 29 feet (8.8 meters).",
        "what's the smallest snake in the world": "The smallest snake is the thread snake, which is about 4 inches (10 centimeters) long.",
        "what's the largest amphibian in the world": "The largest amphibian is the Chinese giant salamander, which can grow up to 6 feet (1.8 meters) in length.",
        "what's the smallest amphibian in the world": "The smallest amphibian is the Paedophryne amauensis, a species of frog that is less than one-third of an inch (7.7 millimeters) long.",
        "what's the largest mammal in the world": "The largest mammal is the blue whale, which is also the largest animal to have ever existed.",
        "what's the smallest mammal in the world": "The smallest mammal is the bumblebee bat, also known as Kitti's hog-nosed bat.",
        "what's the largest fish in the world": "The largest fish is the whale shark, which can grow up to 40 feet (12 meters) in length.",
        "what's the smallest fish in the world": "The smallest fish is the stout floater, which is less than half an inch (1 centimeter) long.",
        "what's the largest bird in the world": "The largest bird is the ostrich, which can weigh over 300 pounds (136 kilograms) and stand up to 9 feet (2.7 meters) tall.",
        "what's the smallest bird in the world": "The smallest bird is the bee hummingbird, which is about 2.4 inches (6 centimeters) long and weighs less than a penny.",
        "what's the largest insect in the world": "The largest insect is the Goliath beetle, which can measure up to 4.3 inches (11 centimeters) in length.",
        "what's the smallest insect in the world": "The smallest insect is the fairyfly, a type of parasitic wasp that is less than one-fiftieth of an inch (0.2 millimeters) long.",
        "what's the largest arachnid in the world": "The largest arachnid is the giant huntsman spider, which can have a leg span of up to 12 inches (30 centimeters).",
        "what's the smallest arachnid in the world": "The smallest arachnid is the Patu digua, a type of spider that is less than one-twentieth of an inch (0.4 millimeters) long.",
        "what's the largest crustacean in the world": "The largest crustacean is the Japanese spider crab, which can have a leg span of up to 12 feet (3.7 meters).",
        "what's the smallest crustacean in the world": "The smallest crustacean is the water flea, which is less than one-thirtieth of an inch (1 millimeter) long.",
        "what's the largest mollusk in the world": "The largest mollusk is the giant squid, which can measure up to 43 feet (13 meters) in length.",
        "what's the smallest mollusk in the world": "The smallest mollusk is the blue-ringed octopus, which is less than 8 inches (20 centimeters) in length.",
        "what's the largest arthropod in the world": "The largest arthropod is the Japanese spider crab, which can have a leg span of up to 12 feet (3.7 meters).",
        "what's the smallest arthropod in the world": "The smallest arthropod is the fairyfly, a type of parasitic wasp that is less than one-fiftieth of an inch (0.2 millimeters) long.",
        "what's the largest terrestrial animal in the world": "The largest terrestrial animal is the African elephant, which can weigh up to 14,000 pounds (6,350 kilograms).",
        "what's the smallest terrestrial animal in the world": "The smallest terrestrial animal is the Etruscan shrew, which weighs less than a penny.",
        "what's the largest marine animal in the world": "The largest marine animal is the blue whale, which is also the largest animal to have ever existed.",
        "what's the smallest marine animal in the world": "The smallest marine animal is difficult to determine, as there are many tiny organisms in the ocean.",
        "what's the largest flying animal in the world": "The largest flying animal is the wandering albatross, which has a wingspan of up to 11 feet (3.4 meters).",
        "what's the smallest flying animal in the world": "The smallest flying animal is the bumblebee bat, also known as Kitti's hog-nosed bat.",
        "default": "I'm sorry, I don't understand. Can you please rephrase?",
        "add": "The sum of {} and {} is {}.",
        "subtract": "The difference between {} and {} is {}.",
        "multiply": "The product of {} and {} is {}.",
        "divide": "The result of dividing {} by {} is {}.",
        "square": "The square of {} is {}.",
        "cube": "The cube of {} is {}.",
        "square root": "The square root of {} is {}.",
        "cube root": "The cube root of {} is {}.",
        "percentage": "{}% of {} is {}.",
        "average": "The average of {} is {}.",
        "maximum": "The maximum value among {} is {}.",
        "minimum": "The minimum value among {} is {}.",
        "factorial": "The factorial of {} is {}.",
        "exponentiation": "{} raised to the power of {} is {}.",
        "logarithm": "The logarithm of {} with base {} is {}.",
        "absolute value": "The absolute value of {} is {}.",
        "round": "Rounding {} to the nearest integer gives {}.",
        "floor division": "Floor division of {} by {} is {}.",
        "modulus": "The modulus of {} and {} is {}.",
        "permutation": "The number of permutations of {} taken {} at a time is {}.",
        "combination": "The number of combinations of {} taken {} at a time is {}.",
        "percentage increase": "The percentage increase from {} to {} is {}%.",
        "percentage decrease": "The percentage decrease from {} to {} is {}%.",
        "simple interest": "The simple interest for principal {} at rate {}% for {} years is {}.",
        "compound interest": "The compound interest for principal {} at rate {}% compounded {} times per year for {} years is {}.",
        "area of rectangle": "The area of a rectangle with length {} and width {} is {}.",
        "perimeter of rectangle": "The perimeter of a rectangle with length {} and width {} is {}.",
        "area of square": "The area of a square with side {} is {}.",
        "perimeter of square": "The perimeter of a square with side {} is {}.",
        "area of circle": "The area of a circle with radius {} is {}.",
        "circumference of circle": "The circumference of a circle with radius {} is {}.",
        "volume of cube": "The volume of a cube with side {} is {}.",
        "surface area of cube": "The surface area of a cube with side {} is {}.",
        "volume of cylinder": "The volume of a cylinder with radius {} and height {} is {}.",
        "surface area of cylinder": "The surface area of a cylinder with radius {} and height {} is {}.",
        "volume of sphere": "The volume of a sphere with radius {} is {}.",
        "surface area of sphere": "The surface area of a sphere with radius {} is {}.",
        "volume of cone": "The volume of a cone with radius {} and height {} is {}.",
        "surface area of cone": "The surface area of a cone with radius {} and height {} is {}.",
        "volume of pyramid": "The volume of a pyramid with base area {} and height {} is {}.",
        "surface area of pyramid": "The surface area of a pyramid with base perimeter {} and slant height {} is {}.",
        "distance": "The distance between points ({}, {}) and ({}, {}) is {}.",
        "midpoint": "The midpoint between points ({}, {}) and ({}, {}) is ({}, {}).",
        "slope": "The slope between points ({}, {}) and ({}, {}) is {}.",
        "y-intercept": "The y-intercept of the line passing through ({}, {}) and ({}, {}) is {}.",
        "x-intercept": "The x-intercept of the line passing through ({}, {}) and ({}, {}) is {}.",
        "distance traveled": "The distance traveled with speed {} km/h for {} hours is {} km.",
        "time taken": "The time taken to travel {} km with speed {} km/h is {} hours.",
        "average speed": "The average speed for traveling {} km in {} hours is {} km/h."
        
    }
        return responses.get(message.lower(), responses['default'])


# Main program
if __name__ == "__main__":
    bot = Chatbot("ChatGPT")
    print(bot.greet())
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'bye':
            print("Bot: Goodbye!")
            break
        else:
            print("Bot:", bot.respond(user_input))
